  server:
    port: 8080
    address: 0.0.0.0
  spring:
    security:
      user:
        name: daniel
        password: daniel@1234
    datasource:
      url: jdbc:mysql://localhost:3307/headfirst
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect